### ISSUE TITLE
Any thoughts on OSC support?

### ISSUE THREAD

**Issue by josephwilk** [darrenmothersele/cyril#18]
Hi,

Any thoughts on Cyril supporting Open Sound Control protocol? 
I've been experimenting with controlling visuals from Clojure programs using OSC and a combination of Fluxus (http://www.pawfal.org/fluxus/) and Shadertone (https://github.com/overtone/shadertone). Cyril looks very nice and smooth but I would need some kind of OSC handlers so I could send all my timing signals (from Overtone) to Cyril.

Any thoughts?
Thanks,
Joseph Wilk

**Comment by darrenmothersele** [comment]
I've added a new beta release (6) that has basic hard-coded OSC support. Plan to make this configurable by adding a settings.xml configuration file. Check this other issue for details of what's been implemented now, and further development: #24

**Comment by josephwilk** [comment]
Oh nice! Thanks
